use std::str::CharIndices;
use std::iter::Peekable;
use operator::Operator;
use operator::Operator::*;
use consts::*;
// use self::Operator::*;

/// Parent enum defining the two types of Terminal symbols within the language.
/// Words, and operator symbols.
#[derive(Debug, PartialEq, Clone)]
pub enum Lexeme {
    /// TODO
    Operator(usize, Operator),
    /// TODO
    Word(usize, String),
}
/// Lexer
pub struct Lexer<'a> {
    input: Peekable<CharIndices<'a>>,
    output: Vec<Lexeme>,
}

impl<'a> Lexer<'a> {
    fn new(input: &'a str) -> Self {
        Lexer {
            input: input.char_indices().peekable(),
            output: Vec::new(),
        }
    }

    fn take(&mut self) -> Option<(usize, char)> {
        self.input.next()
    }

    fn peek(&mut self) -> Option<&(usize, char)> {
        self.input.peek()
    }

    fn push(&mut self, token: Lexeme) {
        self.output.push(token);
    }
    /// Returns the output of the lexer
    pub fn output(&self) -> Vec<Lexeme> {
        self.output.to_vec()
    }

    /// TODO
    pub fn lex(input: &'a str) -> Self {
        let mut lexer = Lexer::new(input);

        while let Some(token) = lexer.take_token() {
            lexer.push(token);
        }

        lexer
    }

    fn take_token(&mut self) -> Option<Lexeme> {
        let mut leading_space = false;
        loop {
            if let Some(&(_, character)) = self.peek() {
                if character.is_whitespace() && character != '\n' {
                    let _ = self.take();
                    leading_space = true;
                } else {
                    break;
                }
            } else {
                return None;
            }
        }

        match self.take() {
            Some((index, AT)) => Some(Lexeme::Operator(index, At)),
            Some((index, BACKSLASH)) => Some(Lexeme::Operator(index, BackSlash)),
            Some((index, CARRAGE_RETURN)) => {
                if self.peek() == Some(&(index, '\n')) {
                    let _ = self.take();
                    Some(Lexeme::Operator(index, Newline))
                } else {
                    panic!("\\r without \\n? Is this 1999?");
                }
            }
            Some((index, CLOSEBRACE)) => Some(Lexeme::Operator(index, CloseBrace)),
            Some((index, CLOSEPARAM)) => Some(Lexeme::Operator(index, CloseParam)),
            Some((index, DOT)) => Some(Lexeme::Operator(index, Dot)),
            Some((index, DOUBLEQUOTE)) => Some(Lexeme::Operator(index, Quote)),
            Some((index, EQUALS)) => Some(Lexeme::Operator(index, Equals)),
            Some((index, FORWARDSLASH)) => Some(Lexeme::Operator(index, ForwardSlash)),
            Some((index, NEWLINE)) => Some(Lexeme::Operator(index, Newline)),
            Some((index, OPENBRACE)) => Some(Lexeme::Operator(index, OpenBrace)),
            Some((index, OPENPARAM)) => Some(Lexeme::Operator(index, OpenParam)),
            Some((index, POUND)) => Some(Lexeme::Operator(index, Pound)),
            Some((index, SINGLEQUOTE)) => Some(Lexeme::Operator(index, Quote)),
            Some((index, STAR)) => Some(Lexeme::Operator(index, Star)),
            Some((index, character)) => {
                let mut word = if leading_space {
                    ' '.to_string()
                } else {
                    String::new()
                };

                word.push(character);

                loop {
                    if let Some(&(_, character)) = self.peek() {
                        match character {
                            // The following case is for determining if a character divides words or
                            // if it is packaged with the words. So things like "Hello}" comes out
                            // as Text: "Hello" Operator: "}"
                            BACKSLASH |
                            CARRAGE_RETURN |
                            CLOSEBRACE |
                            CLOSEPARAM |
                            DOT |
                            DOUBLEQUOTE |
                            EQUALS |
                            FORWARDSLASH |
                            NEWLINE |
                            OPENBRACE |
                            OPENPARAM |
                            POUND |
                            SINGLEQUOTE => {
                                return Some(Lexeme::Word(index, word));
                            }
                            ch => {
                                if !ch.is_whitespace() {
                                    word.push(self.take().unwrap().1);
                                } else {
                                    break;
                                }
                            }
                        }
                    } else {
                        break;
                    }
                }

                if let Some(&(_, ch)) = self.peek() {
                    if ch.is_whitespace() {
                        word.push(ch);
                        let _ = self.take();
                    }
                }
                Some(Lexeme::Word(index, word))
            }
            None => None,
        }
    }
}

#[allow(unused_imports)]
mod tests {
    use super::{Lexer, Lexeme};
    use super::Lexeme::{Word, Operator};
    use operator::Operator::*;

    #[test]
    fn ignore_spaces() {
        let lexer = Lexer::lex(" \t   ");

        assert_eq!(lexer.output(), vec![]);
    }

    #[test]
    fn at_operator() {
        let lexer = Lexer::lex("@");

        assert_eq!(lexer.output(), vec![Operator(0, At)]);
    }
    #[test]
    fn back_slash_operator() {
        let lexer = Lexer::lex("\\");

        assert_eq!(lexer.output(), vec![Operator(0, BackSlash)]);
    }
    #[test]
    fn close_brace_operator() {
        let lexer = Lexer::lex("}");

        assert_eq!(lexer.output(), vec![Operator(0, CloseBrace)]);
    }
    #[test]
    fn close_param_operator() {
        let lexer = Lexer::lex(")");

        assert_eq!(lexer.output(), vec![Operator(0, CloseParam)]);
    }
    #[test]
    fn dot_operator() {
        let lexer = Lexer::lex(".");

        assert_eq!(lexer.output(), vec![Operator(0, Dot)]);
    }
    #[test]
    fn equals_operator() {
        let lexer = Lexer::lex("=");

        assert_eq!(lexer.output(), vec![Operator(0, Equals)]);
    }
    #[test]
    fn forward_slash_operator() {
        let lexer = Lexer::lex("/");

        assert_eq!(lexer.output(), vec![Operator(0, ForwardSlash)]);
    }
    #[test]
    fn new_line_operator() {
        let lexer = Lexer::lex("\n");

        assert_eq!(lexer.output(), vec![Operator(0, Newline)]);
    }
    #[test]
    fn open_brace_operator() {
        let lexer = Lexer::lex("{");

        assert_eq!(lexer.output(), vec![Operator(0, OpenBrace)]);
    }
    #[test]
    fn open_param_operator() {
        let lexer = Lexer::lex("(");

        assert_eq!(lexer.output(), vec![Operator(0, OpenParam)]);
    }
    #[test]
    fn pound_operator() {
        let lexer = Lexer::lex("#");

        assert_eq!(lexer.output(), vec![Operator(0, Pound)]);
    }
    #[test]
    fn quote_operator() {
        let lexer = Lexer::lex("\"");

        assert_eq!(lexer.output(), vec![Operator(0, Quote)]);
    }
    #[test]
    fn single_quote_into_quote_operator() {
        let lexer = Lexer::lex("'");

        assert_eq!(lexer.output(), vec![Operator(0, Quote)]);
    }
    #[test]
    fn star_operator() {
        let lexer = Lexer::lex("*");

        assert_eq!(lexer.output(), vec![Operator(0, Star)]);
    }
    #[test]
    fn all_operators() {
        let lexer = Lexer::lex("@\\}).=/\n{(#\"'*");

        assert_eq!(lexer.output(),
                   vec![Operator(0, At),
                        Operator(1, BackSlash),
                        Operator(2, CloseBrace),
                        Operator(3, CloseParam),
                        Operator(4, Dot),
                        Operator(5, Equals),
                        Operator(6, ForwardSlash),
                        Operator(7, Newline),
                        Operator(8, OpenBrace),
                        Operator(9, OpenParam),
                        Operator(10, Pound),
                        Operator(11, Quote),
                        Operator(12, Quote),
                        Operator(13, Star)]);
    }
    #[test]
    fn word() {
        let lexer = Lexer::lex("Hello");

        assert_eq!(lexer.output(), vec![Word(0, "Hello".to_owned())]);
    }
    #[test]
    fn words() {
        let lexer = Lexer::lex("The Lord Of The Rings");

        assert_eq!(lexer.output(),
                   vec![Word(0, "The ".to_owned()),
                        Word(4, "Lord ".to_owned()),
                        Word(9, "Of ".to_owned()),
                        Word(12, "The ".to_owned()),
                        Word(16, "Rings".to_owned())]);
    }
    #[test]
    fn words_and_operators() {
        let lexer = Lexer::lex("@{Hello}.");

        assert_eq!(lexer.output(),
                   vec![Operator(0, At),
                        Operator(1, OpenBrace),
                        Word(2, "Hello".to_string()),
                        Operator(7, CloseBrace),
                        Operator(8, Dot)]);
    }
    #[test]
    fn hello_world() {
        let lexer = Lexer::lex("/html{\n /body {\n /p{Hello /u{World}!}}}");
        let expected_tokens = vec![Operator(0, ForwardSlash),
                                   Word(1, "html".to_owned()),
                                   Operator(5, OpenBrace),
                                   Operator(6, Newline),
                                   Operator(8, ForwardSlash),
                                   Word(9, "body ".to_owned()),
                                   Operator(14, OpenBrace),
                                   Operator(15, Newline),
                                   Operator(17, ForwardSlash),
                                   Word(18, "p".to_owned()),
                                   Operator(19, OpenBrace),
                                   Word(20, "Hello ".to_owned()),
                                   Operator(26, ForwardSlash),
                                   Word(27, "u".to_owned()),
                                   Operator(28, OpenBrace),
                                   Word(29, "World".to_owned()),
                                   Operator(34, CloseBrace),
                                   Word(35, "!".to_owned()),
                                   Operator(36, CloseBrace),
                                   Operator(37, CloseBrace),
                                   Operator(38, CloseBrace)];
        for (actual, expected) in lexer.output().iter().zip(expected_tokens.iter()) {
            assert_eq!(actual, expected);
        }
    }
    // This test is to check if the syntax of the lexer has meaningfully changed.
    #[test]
    fn huge_file_regression_test() {
        use std::io::Read;
        use std::fs::File;
        let mut file = File::open("./tests/static_site.poly").unwrap();
        let mut contents = String::new();
        let _ = file.read_to_string(&mut contents);
        let lexer = Lexer::lex(&*contents);
        let expected_tokens = vec![Operator(0, ForwardSlash),
                                   Word(1, "!DOCTYPE".to_owned()),
                                   Operator(9, OpenBrace),
                                   Word(10, "html".to_owned()),
                                   Operator(14, CloseBrace),
                                   Operator(16, Newline),
                                   Operator(17, ForwardSlash),
                                   Word(18, "html".to_owned()),
                                   Operator(22, OpenParam),
                                   Word(23, "lang".to_owned()),
                                   Operator(27, Equals),
                                   Operator(28, Quote),
                                   Word(29, "en".to_owned()),
                                   Operator(31, Quote),
                                   Operator(32, CloseParam),
                                   Operator(34, OpenBrace),
                                   Operator(36, Newline),
                                   Operator(41, ForwardSlash),
                                   Word(42, "head ".to_owned()),
                                   Operator(47, OpenBrace),
                                   Operator(49, Newline),
                                   Operator(58, ForwardSlash),
                                   Word(59, "meta".to_owned()),
                                   Operator(63, OpenParam),
                                   Word(64, "charset".to_owned()),
                                   Operator(71, Equals),
                                   Operator(72, Quote),
                                   Word(73, "UTF-8".to_owned()),
                                   Operator(78, Quote),
                                   Operator(79, CloseParam),
                                   Operator(80, OpenBrace),
                                   Operator(81, CloseBrace),
                                   Operator(83, Newline),
                                   Operator(92, ForwardSlash),
                                   Word(93, "title".to_owned()),
                                   Operator(98, OpenBrace),
                                   Word(99, "< ".to_owned()),
                                   Word(101, "httpete ".to_owned()),
                                   Operator(109, ForwardSlash),
                                   Word(110, ">".to_owned()),
                                   Operator(111, CloseBrace),
                                   Operator(113, ForwardSlash),
                                   Operator(114, ForwardSlash),
                                   Word(116, " Viewport ".to_owned()),
                                   Word(125, "tag ".to_owned()),
                                   Word(129, "to ".to_owned()),
                                   Word(132, "make ".to_owned()),
                                   Word(137, "things ".to_owned()),
                                   Word(144, "responsive".to_owned()),
                                   Operator(155, Newline),
                                   Operator(164, ForwardSlash),
                                   Word(165, "meta".to_owned()),
                                   Operator(169, OpenParam),
                                   Word(170, "name".to_owned()),
                                   Operator(174, Equals),
                                   Operator(175, Quote),
                                   Word(176, "viewport".to_owned()),
                                   Operator(184, Quote),
                                   Word(186, " content".to_owned()),
                                   Operator(193, Equals),
                                   Operator(194, Quote),
                                   Word(195, "width".to_owned()),
                                   Operator(200, Equals),
                                   Word(201, "device-width, ".to_owned()),
                                   Word(215, "user-scalable".to_owned()),
                                   Operator(228, Equals),
                                   Word(229, "no".to_owned()),
                                   Operator(231, Quote),
                                   Operator(232, CloseParam),
                                   Operator(233, OpenBrace),
                                   Operator(234, CloseBrace),
                                   Operator(236, Newline),
                                   Operator(238, Newline),
                                   Operator(247, ForwardSlash),
                                   Operator(248, ForwardSlash),
                                   Word(250, " css ".to_owned()),
                                   Word(254, "links".to_owned()),
                                   Operator(260, Newline),
                                   Operator(269, ForwardSlash),
                                   Word(270, "link".to_owned()),
                                   Operator(274, OpenParam),
                                   Word(275, "href".to_owned()),
                                   Operator(279, Equals),
                                   Operator(280, Quote),
                                   Operator(281, ForwardSlash),
                                   Operator(282, ForwardSlash),
                                   Word(283, "cdn".to_owned()),
                                   Operator(286, Dot),
                                   Word(287, "jsdelivr".to_owned()),
                                   Operator(295, Dot),
                                   Word(296, "net".to_owned()),
                                   Operator(299, ForwardSlash),
                                   Word(300, "devicons".to_owned()),
                                   Operator(308, ForwardSlash),
                                   Word(309, "1".to_owned()),
                                   Operator(310, Dot),
                                   Word(311, "7".to_owned()),
                                   Operator(312, Dot),
                                   Word(313, "0".to_owned()),
                                   Operator(314, ForwardSlash),
                                   Word(315, "css".to_owned()),
                                   Operator(318, ForwardSlash),
                                   Word(319, "devicons".to_owned()),
                                   Operator(327, Dot),
                                   Word(328, "min".to_owned()),
                                   Operator(331, Dot),
                                   Word(332, "css".to_owned()),
                                   Operator(335, Quote),
                                   Word(337, " rel".to_owned()),
                                   Operator(340, Equals),
                                   Operator(341, Quote),
                                   Word(342, "stylesheet".to_owned()),
                                   Operator(352, Quote),
                                   Operator(353, CloseParam),
                                   Operator(354, OpenBrace),
                                   Operator(355, CloseBrace),
                                   Operator(357, Newline),
                                   Operator(366, ForwardSlash),
                                   Word(367, "link".to_owned()),
                                   Operator(371, OpenParam),
                                   Word(372, "href".to_owned()),
                                   Operator(376, Equals),
                                   Operator(377, Quote),
                                   Word(378, "http:".to_owned()),
                                   Operator(383, ForwardSlash),
                                   Operator(384, ForwardSlash),
                                   Word(385, "fonts".to_owned()),
                                   Operator(390, Dot),
                                   Word(391, "googleapis".to_owned()),
                                   Operator(401, Dot),
                                   Word(402, "com".to_owned()),
                                   Operator(405, ForwardSlash),
                                   Word(406, "css?family".to_owned()),
                                   Operator(416, Equals),
                                   Word(417, "Lato|Varela+Round".to_owned()),
                                   Operator(434, Quote),
                                   Word(436, " rel".to_owned()),
                                   Operator(439, Equals),
                                   Operator(440, Quote),
                                   Word(441, "stylesheet".to_owned()),
                                   Operator(451, Quote),
                                   Word(453, " type".to_owned()),
                                   Operator(457, Equals),
                                   Operator(458, Quote),
                                   Word(459, "text".to_owned()),
                                   Operator(463, ForwardSlash),
                                   Word(464, "css".to_owned()),
                                   Operator(467, Quote),
                                   Operator(468, CloseParam),
                                   Operator(469, OpenBrace),
                                   Operator(470, CloseBrace),
                                   Operator(472, Newline),
                                   Operator(481, ForwardSlash),
                                   Word(482, "link".to_owned()),
                                   Operator(486, OpenParam),
                                   Word(487, "rel".to_owned()),
                                   Operator(490, Equals),
                                   Operator(491, Quote),
                                   Word(492, "stylesheet".to_owned()),
                                   Operator(502, Quote),
                                   Word(504, " href".to_owned()),
                                   Operator(508, Equals),
                                   Operator(509, Quote),
                                   Operator(510, Dot),
                                   Operator(511, ForwardSlash),
                                   Word(512, "dist".to_owned()),
                                   Operator(516, ForwardSlash),
                                   Word(517, "css".to_owned()),
                                   Operator(520, ForwardSlash),
                                   Word(521, "main".to_owned()),
                                   Operator(525, Dot),
                                   Word(526, "css".to_owned()),
                                   Operator(529, Quote),
                                   Operator(530, CloseParam),
                                   Operator(531, OpenBrace),
                                   Operator(532, CloseBrace),
                                   Operator(534, Newline),
                                   Operator(543, ForwardSlash),
                                   Operator(544, ForwardSlash),
                                   Operator(546, ForwardSlash),
                                   Word(547, "css ".to_owned()),
                                   Word(551, "links".to_owned()),
                                   Operator(557, Newline),
                                   Operator(562, CloseBrace),
                                   Operator(564, Newline),
                                   Operator(566, Newline),
                                   Operator(571, ForwardSlash),
                                   Word(572, "body ".to_owned()),
                                   Operator(577, OpenBrace),
                                   Operator(579, Newline),
                                   Operator(588, ForwardSlash),
                                   Word(589, "header".to_owned()),
                                   Operator(595, Dot),
                                   Word(596, "header ".to_owned()),
                                   Operator(603, OpenBrace),
                                   Operator(605, Newline),
                                   Word(618, " div".to_owned()),
                                   Operator(621, Dot),
                                   Word(622, "header__container ".to_owned()),
                                   Operator(640, OpenBrace),
                                   Operator(642, Newline),
                                   Word(659, " h1".to_owned()),
                                   Operator(661, Dot),
                                   Word(662, "header__title".to_owned()),
                                   Operator(675, OpenBrace),
                                   Word(676, "Peter ".to_owned()),
                                   Word(682, "Redmond".to_owned()),
                                   Operator(689, CloseBrace),
                                   Operator(691, Newline),
                                   Word(708, " h3".to_owned()),
                                   Operator(710, Dot),
                                   Word(711, "header__subtitle".to_owned()),
                                   Operator(727, OpenBrace),
                                   Word(728, "Web ".to_owned()),
                                   Word(732, "Developer".to_owned()),
                                   Operator(741, CloseBrace),
                                   Operator(743, Newline),
                                   Operator(756, CloseBrace),
                                   Operator(758, Newline),
                                   Operator(771, ForwardSlash),
                                   Word(772, "span".to_owned()),
                                   Operator(776, Dot),
                                   Word(777, "header__mouse".to_owned()),
                                   Operator(790, OpenBrace),
                                   Operator(791, CloseBrace),
                                   Operator(793, Newline),
                                   Operator(802, CloseBrace),
                                   Operator(804, Newline),
                                   Operator(813, ForwardSlash),
                                   Word(814, "div".to_owned()),
                                   Operator(817, Dot),
                                   Word(818, "main ".to_owned()),
                                   Operator(823, OpenBrace),
                                   Operator(825, Newline),
                                   Operator(838, ForwardSlash),
                                   Word(839, "section".to_owned()),
                                   Operator(846, Dot),
                                   Word(847, "about ".to_owned()),
                                   Operator(853, OpenBrace),
                                   Operator(855, Newline),
                                   Operator(872, ForwardSlash),
                                   Word(873, "div".to_owned()),
                                   Operator(876, Dot),
                                   Word(877, "container ".to_owned()),
                                   Operator(887, OpenBrace),
                                   Operator(889, Newline),
                                   Operator(910, ForwardSlash),
                                   Word(911, "div".to_owned()),
                                   Operator(914, Dot),
                                   Word(915, "about__container ".to_owned()),
                                   Operator(932, OpenBrace),
                                   Operator(934, Newline),
                                   Word(959, " p".to_owned()),
                                   Operator(960, Dot),
                                   Word(961, "about__content ".to_owned()),
                                   Operator(976, OpenBrace),
                                   Word(977, "Passionate ".to_owned()),
                                   Word(988, "frontend ".to_owned()),
                                   Word(997, "developer ".to_owned()),
                                   Word(1007, "currently ".to_owned()),
                                   Word(1017, "studying ".to_owned()),
                                   Word(1026, "Multimedia ".to_owned()),
                                   Word(1037, "Systems ".to_owned()),
                                   Word(1045, "and ".to_owned()),
                                   Word(1049, "Web ".to_owned()),
                                   Word(1053, "Engineering ".to_owned()),
                                   Word(1065, "in ".to_owned()),
                                   Word(1068, "the ".to_owned()),
                                   Word(1072, "Institute ".to_owned()),
                                   Word(1082, "of ".to_owned()),
                                   Word(1085, "Art, ".to_owned()),
                                   Word(1090, "Design ".to_owned()),
                                   Word(1097, "and ".to_owned()),
                                   Word(1101, "Technology".to_owned()),
                                   Operator(1111, Dot),
                                   Word(1113, " Over ".to_owned()),
                                   Word(1118, "three ".to_owned()),
                                   Word(1124, "years ".to_owned()),
                                   Word(1130, "experience ".to_owned()),
                                   Word(1141, "producing ".to_owned()),
                                   Word(1151, "industry ".to_owned()),
                                   Word(1160, "standard ".to_owned()),
                                   Word(1169, "web ".to_owned()),
                                   Word(1173, "applications ".to_owned()),
                                   Word(1186, "and ".to_owned()),
                                   Word(1190, "websites ".to_owned()),
                                   Word(1199, "using ".to_owned()),
                                   Word(1205, "semantic ".to_owned()),
                                   Word(1214, "markup ".to_owned()),
                                   Word(1221, "and ".to_owned()),
                                   Word(1225, "modular ".to_owned()),
                                   Word(1233, "design ".to_owned()),
                                   Word(1240, "principles".to_owned()),
                                   Operator(1250, Dot),
                                   Word(1252, " Highly ".to_owned()),
                                   Word(1259, "proficient ".to_owned()),
                                   Word(1270, "in ".to_owned()),
                                   Word(1273, "HTML, ".to_owned()),
                                   Word(1279, "CSS ".to_owned()),
                                   Word(1283, "and ".to_owned()),
                                   Word(1287, "JavaScript".to_owned()),
                                   Operator(1297, Dot),
                                   Word(1299, " Below ".to_owned()),
                                   Word(1305, "is ".to_owned()),
                                   Word(1308, "a ".to_owned()),
                                   Word(1310, "selection ".to_owned()),
                                   Word(1320, "of ".to_owned()),
                                   Word(1323, "some ".to_owned()),
                                   Word(1328, "of ".to_owned()),
                                   Word(1331, "the ".to_owned()),
                                   Word(1335, "work ".to_owned()),
                                   Word(1340, "I ".to_owned()),
                                   Word(1342, "have ".to_owned()),
                                   Word(1347, "done ".to_owned()),
                                   Word(1352, "and ".to_owned()),
                                   Word(1356, "more ".to_owned()),
                                   Word(1361, "can ".to_owned()),
                                   Word(1365, "be ".to_owned()),
                                   Word(1368, "seen ".to_owned()),
                                   Word(1373, "on ".to_owned()),
                                   Word(1376, "my ".to_owned()),
                                   Operator(1379, ForwardSlash),
                                   Word(1380, "a".to_owned()),
                                   Operator(1381, Dot),
                                   Word(1382, "github--link".to_owned()),
                                   Operator(1394, OpenParam),
                                   Word(1395, "href".to_owned()),
                                   Operator(1399, Equals),
                                   Operator(1400, Quote),
                                   Word(1401, "https:".to_owned()),
                                   Operator(1407, ForwardSlash),
                                   Operator(1408, ForwardSlash),
                                   Word(1409, "github".to_owned()),
                                   Operator(1415, Dot),
                                   Word(1416, "com".to_owned()),
                                   Operator(1419, ForwardSlash),
                                   Word(1420, "httpete-ire".to_owned()),
                                   Operator(1431, Quote),
                                   Operator(1432, CloseParam),
                                   Operator(1433, OpenBrace),
                                   Word(1434, "GitHub".to_owned()),
                                   Operator(1440, CloseBrace),
                                   Word(1442, " page".to_owned()),
                                   Operator(1446, Dot),
                                   Operator(1447, CloseBrace),
                                   Operator(1449, Newline),
                                   Operator(1470, CloseBrace),
                                   Operator(1472, Newline),
                                   Operator(1474, Newline),
                                   Operator(1495, ForwardSlash),
                                   Word(1496, "div".to_owned()),
                                   Operator(1499, Dot),
                                   Word(1500, "skill__container ".to_owned()),
                                   Operator(1517, OpenBrace),
                                   Operator(1519, Newline),
                                   Operator(1544, ForwardSlash),
                                   Word(1545, "ul".to_owned()),
                                   Operator(1547, Dot),
                                   Word(1548, "skill__list ".to_owned()),
                                   Operator(1560, OpenBrace),
                                   Operator(1562, Newline),
                                   Operator(1591, ForwardSlash),
                                   Word(1592, "li".to_owned()),
                                   Operator(1594, Dot),
                                   Word(1595, "skill__item".to_owned()),
                                   Operator(1606, Dot),
                                   Word(1607, "skill__html".to_owned()),
                                   Operator(1618, OpenBrace),
                                   Operator(1620, Newline),
                                   Operator(1653, ForwardSlash),
                                   Word(1654, "span".to_owned()),
                                   Operator(1658, Dot),
                                   Word(1659, "devicons".to_owned()),
                                   Operator(1667, Dot),
                                   Word(1668, "devicons-html5".to_owned()),
                                   Operator(1682, OpenBrace),
                                   Operator(1683, CloseBrace),
                                   Word(1684, "HTML".to_owned()),
                                   Operator(1689, Newline),
                                   Operator(1718, CloseBrace),
                                   Operator(1720, Newline),
                                   Operator(1749, ForwardSlash),
                                   Word(1750, "li".to_owned()),
                                   Operator(1752, Dot),
                                   Word(1753, "skill__item".to_owned()),
                                   Operator(1764, Dot),
                                   Word(1765, "skill__css".to_owned()),
                                   Operator(1775, OpenBrace),
                                   Operator(1777, Newline),
                                   Operator(1810, ForwardSlash),
                                   Word(1811, "span".to_owned()),
                                   Operator(1815, Dot),
                                   Word(1816, "devicons".to_owned()),
                                   Operator(1824, Dot),
                                   Word(1825, "devicons-css3".to_owned()),
                                   Operator(1838, OpenBrace),
                                   Operator(1839, CloseBrace),
                                   Word(1840, "CSS".to_owned()),
                                   Operator(1844, Newline),
                                   Operator(1873, CloseBrace),
                                   Operator(1875, Newline),
                                   Operator(1904, ForwardSlash),
                                   Word(1905, "li".to_owned()),
                                   Operator(1907, Dot),
                                   Word(1908, "skill__item".to_owned()),
                                   Operator(1919, Dot),
                                   Word(1920, "skill__js".to_owned()),
                                   Operator(1929, OpenBrace),
                                   Operator(1931, Newline),
                                   Operator(1964, ForwardSlash),
                                   Word(1965, "span".to_owned()),
                                   Operator(1969, Dot),
                                   Word(1970, "devicons".to_owned()),
                                   Operator(1978, Dot),
                                   Word(1979, "devicons-javascript_badge".to_owned()),
                                   Operator(2004, OpenBrace),
                                   Operator(2005, CloseBrace),
                                   Word(2006, "JS".to_owned()),
                                   Operator(2009, Newline),
                                   Operator(2038, CloseBrace),
                                   Operator(2040, Newline),
                                   Operator(2069, ForwardSlash),
                                   Word(2070, "li".to_owned()),
                                   Operator(2072, Dot),
                                   Word(2073, "skill__item".to_owned()),
                                   Operator(2084, Dot),
                                   Word(2085, "skill__node".to_owned()),
                                   Operator(2096, OpenBrace),
                                   Operator(2098, Newline),
                                   Operator(2131, ForwardSlash),
                                   Word(2132, "span".to_owned()),
                                   Operator(2136, Dot),
                                   Word(2137, "devicons".to_owned()),
                                   Operator(2145, Dot),
                                   Word(2146, "devicons-nodejs_small".to_owned()),
                                   Operator(2167, OpenBrace),
                                   Operator(2168, CloseBrace),
                                   Word(2169, "Node".to_owned()),
                                   Operator(2173, Dot),
                                   Word(2174, "js".to_owned()),
                                   Operator(2177, Newline),
                                   Operator(2206, CloseBrace),
                                   Operator(2208, Newline),
                                   Operator(2237, ForwardSlash),
                                   Word(2238, "li".to_owned()),
                                   Operator(2240, Dot),
                                   Word(2241, "skill__item".to_owned()),
                                   Operator(2252, Dot),
                                   Word(2253, "skill__ng".to_owned()),
                                   Operator(2262, OpenBrace),
                                   Operator(2264, Newline),
                                   Operator(2297, ForwardSlash),
                                   Word(2298, "span".to_owned()),
                                   Operator(2302, Dot),
                                   Word(2303, "devicons".to_owned()),
                                   Operator(2311, Dot),
                                   Word(2312, "devicons-angular".to_owned()),
                                   Operator(2328, OpenBrace),
                                   Operator(2329, CloseBrace),
                                   Word(2330, "AngularJS".to_owned()),
                                   Operator(2340, Newline),
                                   Operator(2369, CloseBrace),
                                   Operator(2371, Newline),
                                   Operator(2400, ForwardSlash),
                                   Word(2401, "li".to_owned()),
                                   Operator(2403, Dot),
                                   Word(2404, "skill__item".to_owned()),
                                   Operator(2415, Dot),
                                   Word(2416, "skill__sass ".to_owned()),
                                   Operator(2428, OpenBrace),
                                   Operator(2430, Newline),
                                   Operator(2463, ForwardSlash),
                                   Word(2464, "span".to_owned()),
                                   Operator(2468, Dot),
                                   Word(2469, "devicons".to_owned()),
                                   Operator(2477, Dot),
                                   Word(2478, "devicons-sass".to_owned()),
                                   Operator(2491, OpenBrace),
                                   Operator(2492, CloseBrace),
                                   Word(2493, "SASS".to_owned()),
                                   Operator(2498, Newline),
                                   Operator(2527, CloseBrace),
                                   Operator(2529, Newline),
                                   Operator(2558, ForwardSlash),
                                   Word(2559, "li".to_owned()),
                                   Operator(2561, Dot),
                                   Word(2562, "skill__item".to_owned()),
                                   Operator(2573, Dot),
                                   Word(2574, "skill__gulp ".to_owned()),
                                   Operator(2586, OpenBrace),
                                   Operator(2588, Newline),
                                   Operator(2621, ForwardSlash),
                                   Word(2622, "span".to_owned()),
                                   Operator(2626, Dot),
                                   Word(2627, "devicons".to_owned()),
                                   Operator(2635, Dot),
                                   Word(2636, "devicons-gulp".to_owned()),
                                   Operator(2649, OpenBrace),
                                   Operator(2650, CloseBrace),
                                   Word(2651, "Gulp".to_owned()),
                                   Operator(2656, Newline),
                                   Operator(2685, CloseBrace),
                                   Operator(2687, Newline),
                                   Operator(2716, ForwardSlash),
                                   Word(2717, "li".to_owned()),
                                   Operator(2719, Dot),
                                   Word(2720, "skill__item".to_owned()),
                                   Operator(2731, Dot),
                                   Word(2732, "skill__mongo".to_owned()),
                                   Operator(2744, OpenBrace),
                                   Operator(2746, Newline),
                                   Operator(2779, ForwardSlash),
                                   Word(2780, "span".to_owned()),
                                   Operator(2784, Dot),
                                   Word(2785, "devicons".to_owned()),
                                   Operator(2793, Dot),
                                   Word(2794, "devicons-mongodb".to_owned()),
                                   Operator(2810, OpenBrace),
                                   Operator(2811, CloseBrace),
                                   Word(2812, "MongoDB".to_owned()),
                                   Operator(2820, Newline),
                                   Operator(2849, CloseBrace),
                                   Operator(2851, Newline),
                                   Operator(2876, CloseBrace),
                                   Operator(2878, Newline),
                                   Operator(2899, CloseBrace),
                                   Operator(2901, Newline),
                                   Operator(2922, ForwardSlash),
                                   Operator(2923, ForwardSlash),
                                   Operator(2925, ForwardSlash),
                                   Operator(2926, Dot),
                                   Word(2927, "about__container".to_owned()),
                                   Operator(2944, Newline),
                                   Operator(2961, CloseBrace),
                                   Operator(2963, Newline),
                                   Operator(2976, CloseBrace),
                                   Operator(2978, Newline),
                                   Operator(2991, ForwardSlash),
                                   Word(2992, "section".to_owned()),
                                   Operator(2999, Dot),
                                   Word(3000, "work ".to_owned()),
                                   Operator(3005, OpenBrace),
                                   Operator(3007, Newline),
                                   Operator(3024, ForwardSlash),
                                   Word(3025, "div".to_owned()),
                                   Operator(3028, Dot),
                                   Word(3029, "work__container ".to_owned()),
                                   Operator(3045, OpenBrace),
                                   Operator(3047, Newline),
                                   Operator(3068, ForwardSlash),
                                   Word(3069, "section".to_owned()),
                                   Operator(3076, Dot),
                                   Word(3077, "work__section ".to_owned()),
                                   Operator(3091, OpenBrace),
                                   Operator(3093, Newline),
                                   Operator(3118, ForwardSlash),
                                   Word(3119, "img".to_owned()),
                                   Operator(3122, OpenParam),
                                   Word(3124, " src".to_owned()),
                                   Operator(3127, Equals),
                                   Operator(3128, Quote),
                                   Operator(3129, Dot),
                                   Operator(3130, ForwardSlash),
                                   Word(3131, "dist".to_owned()),
                                   Operator(3135, ForwardSlash),
                                   Word(3136, "img".to_owned()),
                                   Operator(3139, ForwardSlash),
                                   Word(3140, "coapp".to_owned()),
                                   Operator(3145, Dot),
                                   Word(3146, "jpg".to_owned()),
                                   Operator(3149, Quote),
                                   Word(3151, " alt".to_owned()),
                                   Operator(3154, Equals),
                                   Operator(3155, Quote),
                                   Operator(3156, Quote),
                                   Word(3158, " class".to_owned()),
                                   Operator(3163, Equals),
                                   Operator(3164, Quote),
                                   Word(3165, "work__img".to_owned()),
                                   Operator(3174, Quote),
                                   Operator(3175, CloseParam),
                                   Operator(3176, OpenBrace),
                                   Operator(3177, CloseBrace),
                                   Operator(3179, Newline),
                                   Operator(3200, CloseBrace),
                                   Operator(3202, Newline),
                                   Operator(3204, Newline),
                                   Operator(3225, ForwardSlash),
                                   Word(3226, "section".to_owned()),
                                   Operator(3233, Dot),
                                   Word(3234, "work__section".to_owned()),
                                   Operator(3247, Dot),
                                   Word(3248, "work__section--flip ".to_owned()),
                                   Operator(3268, OpenBrace),
                                   Operator(3270, Newline),
                                   Operator(3295, ForwardSlash),
                                   Word(3296, "div".to_owned()),
                                   Operator(3299, Dot),
                                   Word(3300, "work__content ".to_owned()),
                                   Operator(3314, OpenBrace),
                                   Operator(3316, Newline),
                                   Operator(3345, ForwardSlash),
                                   Word(3346, "h3".to_owned()),
                                   Operator(3348, Dot),
                                   Word(3349, "work__title".to_owned()),
                                   Operator(3360, OpenBrace),
                                   Word(3361, "Coapp".to_owned()),
                                   Operator(3366, CloseBrace),
                                   Operator(3368, Newline),
                                   Operator(3370, Newline),
                                   Operator(3399, ForwardSlash),
                                   Word(3400, "p".to_owned()),
                                   Operator(3401, OpenBrace),
                                   Word(3402, "A ".to_owned()),
                                   Word(3404, "collaboration ".to_owned()),
                                   Word(3418, "tool ".to_owned()),
                                   Word(3423, "for ".to_owned()),
                                   Word(3427, "the ".to_owned()),
                                   Word(3431, "design ".to_owned()),
                                   Word(3438, "stage ".to_owned()),
                                   Word(3444, "of ".to_owned()),
                                   Word(3447, "a ".to_owned()),
                                   Word(3449, "project ".to_owned()),
                                   Word(3457, "that ".to_owned()),
                                   Word(3462, "allows ".to_owned()),
                                   Word(3469, "users ".to_owned()),
                                   Word(3475, "to ".to_owned()),
                                   Word(3478, "leave ".to_owned()),
                                   Word(3484, "feedback ".to_owned()),
                                   Word(3493, "and ".to_owned()),
                                   Word(3497, "assign ".to_owned()),
                                   Word(3504, "tasks ".to_owned()),
                                   Word(3510, "to ".to_owned()),
                                   Word(3513, "other ".to_owned()),
                                   Word(3519, "collaborators".to_owned()),
                                   Operator(3532, Dot),
                                   Word(3534, " The ".to_owned()),
                                   Word(3538, "app ".to_owned()),
                                   Word(3542, "was ".to_owned()),
                                   Word(3546, "built ".to_owned()),
                                   Word(3552, "using ".to_owned()),
                                   Word(3558, "an ".to_owned()),
                                   Word(3561, "Angular ".to_owned()),
                                   Word(3569, "frontend ".to_owned()),
                                   Word(3578, "that ".to_owned()),
                                   Word(3583, "connects ".to_owned()),
                                   Word(3592, "to ".to_owned()),
                                   Word(3595, "a ".to_owned()),
                                   Word(3597, "RESTful ".to_owned()),
                                   Word(3605, "API ".to_owned()),
                                   Word(3609, "on ".to_owned()),
                                   Word(3612, "a ".to_owned()),
                                   Word(3614, "node ".to_owned()),
                                   Word(3619, "server".to_owned()),
                                   Operator(3625, Dot),
                                   Operator(3626, CloseBrace),
                                   Operator(3628, Newline),
                                   Operator(3630, Newline),
                                   Operator(3659, ForwardSlash),
                                   Word(3660, "a".to_owned()),
                                   Operator(3661, Dot),
                                   Word(3662, "btn".to_owned()),
                                   Operator(3665, OpenParam),
                                   Word(3666, "href".to_owned()),
                                   Operator(3670, Equals),
                                   Operator(3671, Quote),
                                   Word(3672, "http:".to_owned()),
                                   Operator(3677, ForwardSlash),
                                   Operator(3678, ForwardSlash),
                                   Word(3679, "178".to_owned()),
                                   Operator(3682, Dot),
                                   Word(3683, "62".to_owned()),
                                   Operator(3685, Dot),
                                   Word(3686, "109".to_owned()),
                                   Operator(3689, Dot),
                                   Word(3690, "129:8080".to_owned()),
                                   Operator(3698, ForwardSlash),
                                   Operator(3699, Quote),
                                   Word(3701, " target".to_owned()),
                                   Operator(3707, Equals),
                                   Operator(3708, Quote),
                                   Word(3709, "_blank".to_owned()),
                                   Operator(3715, Quote),
                                   Operator(3716, CloseParam),
                                   Operator(3717, OpenBrace),
                                   Word(3718, "View ".to_owned()),
                                   Word(3723, "app".to_owned()),
                                   Operator(3726, CloseBrace),
                                   Operator(3728, Newline),
                                   Operator(3757, ForwardSlash),
                                   Word(3758, "a".to_owned()),
                                   Operator(3759, Dot),
                                   Word(3760, "link".to_owned()),
                                   Operator(3764, OpenParam),
                                   Word(3765, "href".to_owned()),
                                   Operator(3769, Equals),
                                   Operator(3770, Quote),
                                   Word(3771, "https:".to_owned()),
                                   Operator(3777, ForwardSlash),
                                   Operator(3778, ForwardSlash),
                                   Word(3779, "github".to_owned()),
                                   Operator(3785, Dot),
                                   Word(3786, "com".to_owned()),
                                   Operator(3789, ForwardSlash),
                                   Word(3790, "httpete-ire".to_owned()),
                                   Operator(3801, ForwardSlash),
                                   Word(3802, "coapp".to_owned()),
                                   Operator(3807, Quote),
                                   Word(3809, " target".to_owned()),
                                   Operator(3815, Equals),
                                   Operator(3816, Quote),
                                   Word(3817, "_blank".to_owned()),
                                   Operator(3823, Quote),
                                   Operator(3824, CloseParam),
                                   Operator(3825, OpenBrace),
                                   Word(3826, "Source ".to_owned()),
                                   Word(3833, "code".to_owned()),
                                   Operator(3837, CloseBrace),
                                   Operator(3839, Newline),
                                   Operator(3864, CloseBrace),
                                   Operator(3866, Newline),
                                   Operator(3887, CloseBrace),
                                   Operator(3889, Newline),
                                   Operator(3906, CloseBrace),
                                   Operator(3908, Newline),
                                   Operator(3910, Newline),
                                   Operator(3927, ForwardSlash),
                                   Word(3928, "div".to_owned()),
                                   Operator(3931, Dot),
                                   Word(3932, "work__container ".to_owned()),
                                   Operator(3948, OpenBrace),
                                   Operator(3950, Newline),
                                   Operator(3971, ForwardSlash),
                                   Word(3972, "section".to_owned()),
                                   Operator(3979, Dot),
                                   Word(3980, "work__section ".to_owned()),
                                   Operator(3994, OpenBrace),
                                   Operator(3996, Newline),
                                   Operator(4021, ForwardSlash),
                                   Word(4022, "img".to_owned()),
                                   Operator(4025, OpenParam),
                                   Word(4026, "src".to_owned()),
                                   Operator(4029, Equals),
                                   Operator(4030, Quote),
                                   Operator(4031, Dot),
                                   Operator(4032, ForwardSlash),
                                   Word(4033, "dist".to_owned()),
                                   Operator(4037, ForwardSlash),
                                   Word(4038, "img".to_owned()),
                                   Operator(4041, ForwardSlash),
                                   Word(4042, "pomodoro".to_owned()),
                                   Operator(4050, Dot),
                                   Word(4051, "jpg".to_owned()),
                                   Operator(4054, Quote),
                                   Word(4056, " alt".to_owned()),
                                   Operator(4059, Equals),
                                   Operator(4060, Quote),
                                   Operator(4061, Quote),
                                   Word(4063, " class".to_owned()),
                                   Operator(4068, Equals),
                                   Operator(4069, Quote),
                                   Word(4070, "work__img".to_owned()),
                                   Operator(4079, Quote),
                                   Operator(4080, CloseParam),
                                   Operator(4081, OpenBrace),
                                   Operator(4082, CloseBrace),
                                   Operator(4084, Newline),
                                   Operator(4105, CloseBrace),
                                   Operator(4107, Newline),
                                   Operator(4109, Newline),
                                   Operator(4130, ForwardSlash),
                                   Word(4131, "section".to_owned()),
                                   Operator(4138, Dot),
                                   Word(4139, "work__section ".to_owned()),
                                   Operator(4153, OpenBrace),
                                   Operator(4155, Newline),
                                   Operator(4180, ForwardSlash),
                                   Word(4181, "div".to_owned()),
                                   Operator(4184, Dot),
                                   Word(4185, "work__content ".to_owned()),
                                   Operator(4199, OpenBrace),
                                   Operator(4201, Newline),
                                   Operator(4230, ForwardSlash),
                                   Word(4231, "h3".to_owned()),
                                   Operator(4233, Dot),
                                   Word(4234, "work__title ".to_owned()),
                                   Operator(4246, OpenBrace),
                                   Word(4247, "Pomodoro ".to_owned()),
                                   Word(4256, "timer".to_owned()),
                                   Operator(4261, CloseBrace),
                                   Operator(4263, Newline),
                                   Operator(4265, Newline),
                                   Operator(4294, ForwardSlash),
                                   Word(4295, "p".to_owned()),
                                   Operator(4296, OpenBrace),
                                   Word(4297, "The ".to_owned()),
                                   Word(4301, "pomodoro ".to_owned()),
                                   Word(4310, "technique ".to_owned()),
                                   Word(4320, "is ".to_owned()),
                                   Word(4323, "a ".to_owned()),
                                   Word(4325, "time ".to_owned()),
                                   Word(4330, "management ".to_owned()),
                                   Word(4341, "method ".to_owned()),
                                   Word(4348, "for ".to_owned()),
                                   Word(4352, "breaking ".to_owned()),
                                   Word(4361, "down ".to_owned()),
                                   Word(4366, "large ".to_owned()),
                                   Word(4372, "tasks ".to_owned()),
                                   Word(4378, "into ".to_owned()),
                                   Word(4383, "small, ".to_owned()),
                                   Word(4390, "timed ".to_owned()),
                                   Word(4396, "intervals ".to_owned()),
                                   Word(4406, "that ".to_owned()),
                                   Word(4411, "are ".to_owned()),
                                   Word(4415, "seperated ".to_owned()),
                                   Word(4425, "by ".to_owned()),
                                   Word(4428, "a ".to_owned()),
                                   Word(4430, "short ".to_owned()),
                                   Word(4436, "break".to_owned()),
                                   Operator(4441, Dot),
                                   Word(4443, " I ".to_owned()),
                                   Word(4445, "built ".to_owned()),
                                   Word(4451, "this ".to_owned()),
                                   Word(4456, "app ".to_owned()),
                                   Word(4460, "using ".to_owned()),
                                   Word(4466, "angularJS ".to_owned()),
                                   Word(4476, "to ".to_owned()),
                                   Word(4479, "track ".to_owned()),
                                   Word(4485, "my ".to_owned()),
                                   Word(4488, "time ".to_owned()),
                                   Word(4493, "while ".to_owned()),
                                   Word(4499, "working".to_owned()),
                                   Operator(4506, BackSlash),
                                   Operator(4507, ForwardSlash),
                                   Word(4508, "studying".to_owned()),
                                   Operator(4516, CloseBrace),
                                   Operator(4518, Newline),
                                   Operator(4520, Newline),
                                   Operator(4549, ForwardSlash),
                                   Word(4550, "a".to_owned()),
                                   Operator(4551, Dot),
                                   Word(4552, "btn".to_owned()),
                                   Operator(4555, OpenParam),
                                   Word(4556, "href".to_owned()),
                                   Operator(4560, Equals),
                                   Operator(4561, Quote),
                                   Operator(4562, ForwardSlash),
                                   Word(4563, "pomodoro".to_owned()),
                                   Operator(4571, Quote),
                                   Word(4573, " target".to_owned()),
                                   Operator(4579, Equals),
                                   Operator(4580, Quote),
                                   Word(4581, "_blank".to_owned()),
                                   Operator(4587, Quote),
                                   Operator(4588, CloseParam),
                                   Operator(4589, OpenBrace),
                                   Word(4590, "View ".to_owned()),
                                   Word(4595, "app".to_owned()),
                                   Operator(4598, CloseBrace),
                                   Operator(4600, Newline),
                                   Operator(4629, ForwardSlash),
                                   Word(4630, "a".to_owned()),
                                   Operator(4631, Dot),
                                   Word(4632, "link".to_owned()),
                                   Operator(4636, OpenParam),
                                   Word(4637, "href".to_owned()),
                                   Operator(4641, Equals),
                                   Operator(4642, Quote),
                                   Word(4643, "https:".to_owned()),
                                   Operator(4649, ForwardSlash),
                                   Operator(4650, ForwardSlash),
                                   Word(4651, "github".to_owned()),
                                   Operator(4657, Dot),
                                   Word(4658, "com".to_owned()),
                                   Operator(4661, ForwardSlash),
                                   Word(4662, "httpete-ire".to_owned()),
                                   Operator(4673, ForwardSlash),
                                   Word(4674, "pomodoro".to_owned()),
                                   Operator(4682, Quote),
                                   Word(4684, " target".to_owned()),
                                   Operator(4690, Equals),
                                   Operator(4691, Quote),
                                   Word(4692, "_blank".to_owned()),
                                   Operator(4698, Quote),
                                   Operator(4699, CloseParam),
                                   Operator(4700, OpenBrace),
                                   Word(4701, "Source ".to_owned()),
                                   Word(4708, "code".to_owned()),
                                   Operator(4712, CloseBrace),
                                   Operator(4714, Newline),
                                   Operator(4739, CloseBrace),
                                   Operator(4761, Newline),
                                   Operator(4782, CloseBrace),
                                   Operator(4784, Newline),
                                   Operator(4801, CloseBrace),
                                   Operator(4803, Newline),
                                   Operator(4805, Newline),
                                   Operator(4822, ForwardSlash),
                                   Word(4823, "div".to_owned()),
                                   Operator(4826, Dot),
                                   Word(4827, "work__container ".to_owned()),
                                   Operator(4843, OpenBrace),
                                   Operator(4845, Newline),
                                   Operator(4866, ForwardSlash),
                                   Word(4867, "section".to_owned()),
                                   Operator(4874, Dot),
                                   Word(4875, "work__section ".to_owned()),
                                   Operator(4889, OpenBrace),
                                   Operator(4891, Newline),
                                   Operator(4916, ForwardSlash),
                                   Word(4917, "img".to_owned()),
                                   Operator(4920, Dot),
                                   Word(4921, "work__img".to_owned()),
                                   Operator(4930, OpenParam),
                                   Word(4931, "src".to_owned()),
                                   Operator(4934, Equals),
                                   Operator(4935, Quote),
                                   Operator(4936, Dot),
                                   Operator(4937, ForwardSlash),
                                   Word(4938, "dist".to_owned()),
                                   Operator(4942, ForwardSlash),
                                   Word(4943, "img".to_owned()),
                                   Operator(4946, ForwardSlash),
                                   Word(4947, "urban".to_owned()),
                                   Operator(4952, Dot),
                                   Word(4953, "jpg".to_owned()),
                                   Operator(4956, Quote),
                                   Word(4958, " alt".to_owned()),
                                   Operator(4961, Equals),
                                   Operator(4962, Quote),
                                   Operator(4963, Quote),
                                   Operator(4964, CloseParam),
                                   Operator(4965, OpenBrace),
                                   Operator(4966, CloseBrace),
                                   Operator(4968, Newline),
                                   Operator(4989, CloseBrace),
                                   Operator(4991, Newline),
                                   Operator(4993, Newline),
                                   Operator(5014, ForwardSlash),
                                   Word(5015, "section".to_owned()),
                                   Operator(5022, Dot),
                                   Word(5023, "work__section".to_owned()),
                                   Operator(5036, Dot),
                                   Word(5037, "work__section--flip ".to_owned()),
                                   Operator(5057, OpenBrace),
                                   Operator(5059, Newline),
                                   Operator(5084, ForwardSlash),
                                   Word(5085, "div".to_owned()),
                                   Operator(5088, Dot),
                                   Word(5089, "work__content ".to_owned()),
                                   Operator(5103, OpenBrace),
                                   Operator(5105, Newline),
                                   Operator(5134, ForwardSlash),
                                   Word(5135, "h3".to_owned()),
                                   Operator(5137, Dot),
                                   Word(5138, "work__title".to_owned()),
                                   Operator(5149, OpenBrace),
                                   Word(5150, "Urban ".to_owned()),
                                   Word(5156, "Games".to_owned()),
                                   Operator(5161, CloseBrace),
                                   Operator(5163, Newline),
                                   Operator(5165, Newline),
                                   Operator(5194, ForwardSlash),
                                   Word(5195, "p".to_owned()),
                                   Operator(5196, OpenBrace),
                                   Word(5197, "Urban ".to_owned()),
                                   Word(5203, "Games ".to_owned()),
                                   Word(5209, "is ".to_owned()),
                                   Word(5212, "a ".to_owned()),
                                   Word(5214, "fresh, ".to_owned()),
                                   Word(5221, "dynamic ".to_owned()),
                                   Word(5229, "and ".to_owned()),
                                   Word(5233, "creative ".to_owned()),
                                   Word(5242, "entertainment ".to_owned()),
                                   Word(5256, "company ".to_owned()),
                                   Word(5264, "based ".to_owned()),
                                   Word(5270, "in ".to_owned()),
                                   Word(5273, "dublin".to_owned()),
                                   Operator(5279, Dot),
                                   Word(5281, " I ".to_owned()),
                                   Word(5283, "redesigned ".to_owned()),
                                   Word(5294, "the ".to_owned()),
                                   Word(5298, "whole ".to_owned()),
                                   Word(5304, "front ".to_owned()),
                                   Word(5310, "end ".to_owned()),
                                   Word(5314, "and ".to_owned()),
                                   Word(5318, "implemented ".to_owned()),
                                   Word(5330, "it ".to_owned()),
                                   Word(5333, "to ".to_owned()),
                                   Word(5336, "work ".to_owned()),
                                   Word(5341, "with ".to_owned()),
                                   Word(5346, "their ".to_owned()),
                                   Word(5352, "custom ".to_owned()),
                                   Word(5359, "PHP ".to_owned()),
                                   Word(5363, "backend ".to_owned()),
                                   Word(5371, "system".to_owned()),
                                   Operator(5377, Dot),
                                   Operator(5378, CloseBrace),
                                   Operator(5380, Newline),
                                   Operator(5382, Newline),
                                   Operator(5411, ForwardSlash),
                                   Word(5412, "a".to_owned()),
                                   Operator(5413, Dot),
                                   Word(5414, "btn".to_owned()),
                                   Operator(5417, OpenParam),
                                   Word(5418, "href".to_owned()),
                                   Operator(5422, Equals),
                                   Operator(5423, Quote),
                                   Word(5424, "http:".to_owned()),
                                   Operator(5429, ForwardSlash),
                                   Operator(5430, ForwardSlash),
                                   Word(5431, "www".to_owned()),
                                   Operator(5434, Dot),
                                   Word(5435, "urbangames".to_owned()),
                                   Operator(5445, Dot),
                                   Word(5446, "ie".to_owned()),
                                   Operator(5448, ForwardSlash),
                                   Operator(5449, Quote),
                                   Word(5451, " target".to_owned()),
                                   Operator(5457, Equals),
                                   Operator(5458, Quote),
                                   Word(5459, "_blank".to_owned()),
                                   Operator(5465, Quote),
                                   Operator(5466, CloseParam),
                                   Operator(5467, OpenBrace),
                                   Word(5468, "Visit ".to_owned()),
                                   Word(5474, "site".to_owned()),
                                   Operator(5478, CloseBrace),
                                   Operator(5480, Newline),
                                   Operator(5505, CloseBrace),
                                   Operator(5507, Newline),
                                   Operator(5528, CloseBrace),
                                   Operator(5530, Newline),
                                   Operator(5551, ForwardSlash),
                                   Operator(5552, ForwardSlash),
                                   Operator(5554, ForwardSlash),
                                   Operator(5555, Dot),
                                   Word(5556, "container".to_owned()),
                                   Operator(5566, Newline),
                                   Operator(5583, CloseBrace),
                                   Operator(5585, Newline),
                                   Operator(5598, CloseBrace),
                                   Operator(5600, Newline),
                                   Operator(5609, CloseBrace),
                                   Operator(5611, Newline),
                                   Operator(5620, ForwardSlash),
                                   Word(5621, "footer".to_owned()),
                                   Operator(5627, Dot),
                                   Word(5628, "footer ".to_owned()),
                                   Operator(5635, OpenBrace),
                                   Operator(5637, Newline),
                                   Operator(5650, ForwardSlash),
                                   Word(5651, "div".to_owned()),
                                   Operator(5654, Dot),
                                   Word(5655, "footer--fixed ".to_owned()),
                                   Operator(5669, OpenBrace),
                                   Operator(5671, Newline),
                                   Operator(5688, ForwardSlash),
                                   Word(5689, "div".to_owned()),
                                   Operator(5692, Dot),
                                   Word(5693, "footer__container ".to_owned()),
                                   Operator(5711, OpenBrace),
                                   Operator(5713, Newline),
                                   Operator(5734, ForwardSlash),
                                   Word(5735, "h2".to_owned()),
                                   Operator(5737, Dot),
                                   Word(5738, "footer__title".to_owned()),
                                   Operator(5751, OpenBrace),
                                   Word(5752, "Contact ".to_owned()),
                                   Word(5760, "me".to_owned()),
                                   Operator(5762, CloseBrace),
                                   Operator(5764, Newline),
                                   Operator(5766, Newline),
                                   Operator(5787, ForwardSlash),
                                   Word(5788, "div".to_owned()),
                                   Operator(5791, Dot),
                                   Word(5792, "social__icon-list ".to_owned()),
                                   Operator(5810, OpenBrace),
                                   Operator(5812, Newline),
                                   Operator(5837, ForwardSlash),
                                   Word(5838, "a".to_owned()),
                                   Operator(5839, Dot),
                                   Word(5840, "icon__container".to_owned()),
                                   Operator(5855, OpenParam),
                                   Word(5856, "href".to_owned()),
                                   Operator(5860, Equals),
                                   Operator(5861, Quote),
                                   Word(5862, "https:".to_owned()),
                                   Operator(5868, ForwardSlash),
                                   Operator(5869, ForwardSlash),
                                   Word(5870, "twitter".to_owned()),
                                   Operator(5877, Dot),
                                   Word(5878, "com".to_owned()),
                                   Operator(5881, ForwardSlash),
                                   Word(5882, "_httpete_".to_owned()),
                                   Operator(5891, Quote),
                                   Word(5893, " target".to_owned()),
                                   Operator(5899, Equals),
                                   Operator(5900, Quote),
                                   Word(5901, "_blank".to_owned()),
                                   Operator(5907, Quote),
                                   Operator(5908, CloseParam),
                                   Operator(5910, OpenBrace),
                                   Operator(5912, Newline),
                                   Operator(5941, ForwardSlash),
                                   Word(5942, "img".to_owned()),
                                   Operator(5945, Dot),
                                   Word(5946, "icon__img".to_owned()),
                                   Operator(5955, OpenParam),
                                   Word(5956, "src".to_owned()),
                                   Operator(5959, Equals),
                                   Operator(5960, Quote),
                                   Word(5961, "dist".to_owned()),
                                   Operator(5965, ForwardSlash),
                                   Word(5966, "img".to_owned()),
                                   Operator(5969, ForwardSlash),
                                   Word(5970, "twitter".to_owned()),
                                   Operator(5977, Dot),
                                   Word(5978, "svg".to_owned()),
                                   Operator(5981, Quote),
                                   Operator(5982, CloseParam),
                                   Operator(5983, OpenBrace),
                                   Operator(5984, CloseBrace),
                                   Operator(5986, Newline),
                                   Operator(6011, CloseBrace),
                                   Operator(6013, Newline),
                                   Operator(6038, ForwardSlash),
                                   Word(6039, "a".to_owned()),
                                   Operator(6040, Dot),
                                   Word(6041, "icon__container".to_owned()),
                                   Operator(6056, OpenParam),
                                   Word(6057, "href".to_owned()),
                                   Operator(6061, Equals),
                                   Operator(6062, Quote),
                                   Word(6063, "https:".to_owned()),
                                   Operator(6069, ForwardSlash),
                                   Operator(6070, ForwardSlash),
                                   Word(6071, "github".to_owned()),
                                   Operator(6077, Dot),
                                   Word(6078, "com".to_owned()),
                                   Operator(6081, ForwardSlash),
                                   Word(6082, "httpete-ire".to_owned()),
                                   Operator(6093, Quote),
                                   Word(6095, " target".to_owned()),
                                   Operator(6101, Equals),
                                   Operator(6102, Quote),
                                   Word(6103, "_blank".to_owned()),
                                   Operator(6109, Quote),
                                   Operator(6110, CloseParam),
                                   Operator(6112, OpenBrace),
                                   Operator(6114, Newline),
                                   Operator(6143, ForwardSlash),
                                   Word(6144, "img".to_owned()),
                                   Operator(6147, Dot),
                                   Word(6148, "icon__img".to_owned()),
                                   Operator(6157, OpenParam),
                                   Word(6158, "src".to_owned()),
                                   Operator(6161, Equals),
                                   Operator(6162, Quote),
                                   Word(6163, "dist".to_owned()),
                                   Operator(6167, ForwardSlash),
                                   Word(6168, "img".to_owned()),
                                   Operator(6171, ForwardSlash),
                                   Word(6172, "github".to_owned()),
                                   Operator(6178, Dot),
                                   Word(6179, "svg".to_owned()),
                                   Operator(6182, Quote),
                                   Operator(6183, CloseParam),
                                   Operator(6184, OpenBrace),
                                   Operator(6185, CloseBrace),
                                   Operator(6187, Newline),
                                   Operator(6212, CloseBrace),
                                   Operator(6214, Newline),
                                   Operator(6235, CloseBrace),
                                   Operator(6237, Newline),
                                   Operator(6254, CloseBrace),
                                   Operator(6256, Newline),
                                   Operator(6269, CloseBrace),
                                   Operator(6271, Newline),
                                   Operator(6280, CloseBrace),
                                   Operator(6282, Newline),
                                   Operator(6284, Newline),
                                   Operator(6293, ForwardSlash),
                                   Word(6294, "script ".to_owned()),
                                   Operator(6301, OpenBrace),
                                   Operator(6303, Newline),
                                   Operator(6316, OpenParam),
                                   Word(6317, "function".to_owned()),
                                   Operator(6325, OpenParam),
                                   Word(6326, "i,s,o,g,r,a,m".to_owned()),
                                   Operator(6339, CloseParam),
                                   Operator(6340, OpenBrace),
                                   Word(6341, "i[".to_owned()),
                                   Operator(6343, Quote),
                                   Word(6344, "GoogleAnalyticsObject".to_owned()),
                                   Operator(6365, Quote),
                                   Word(6366, "]".to_owned()),
                                   Operator(6367, Equals),
                                   Word(6368, "r;i[r]".to_owned()),
                                   Operator(6374, Equals),
                                   Word(6375, "i[r]||function".to_owned()),
                                   Operator(6389, OpenParam),
                                   Operator(6390, CloseParam),
                                   Operator(6391, OpenBrace),
                                   Operator(6393, Newline),
                                   Operator(6406, OpenParam),
                                   Word(6407, "i[r]".to_owned()),
                                   Operator(6411, Dot),
                                   Word(6412, "q".to_owned()),
                                   Operator(6413, Equals),
                                   Word(6414, "i[r]".to_owned()),
                                   Operator(6418, Dot),
                                   Word(6419, "q||[]".to_owned()),
                                   Operator(6424, CloseParam),
                                   Operator(6425, Dot),
                                   Word(6426, "push".to_owned()),
                                   Operator(6430, OpenParam),
                                   Word(6431, "arguments".to_owned()),
                                   Operator(6440, CloseParam),
                                   Operator(6441, CloseBrace),
                                   Word(6442, ",i[r]".to_owned()),
                                   Operator(6447, Dot),
                                   Word(6448, "l".to_owned()),
                                   Operator(6449, Equals),
                                   Word(6450, "1*new ".to_owned()),
                                   Word(6456, "Date".to_owned()),
                                   Operator(6460, OpenParam),
                                   Operator(6461, CloseParam),
                                   Word(6462, ";a".to_owned()),
                                   Operator(6464, Equals),
                                   Word(6465, "s".to_owned()),
                                   Operator(6466, Dot),
                                   Word(6467, "createElement".to_owned()),
                                   Operator(6480, OpenParam),
                                   Word(6481, "o".to_owned()),
                                   Operator(6482, CloseParam),
                                   Word(6483, ",".to_owned()),
                                   Operator(6485, Newline),
                                   Word(6498, " m".to_owned()),
                                   Operator(6499, Equals),
                                   Word(6500, "s".to_owned()),
                                   Operator(6501, Dot),
                                   Word(6502, "getElementsByTagName".to_owned()),
                                   Operator(6522, OpenParam),
                                   Word(6523, "o".to_owned()),
                                   Operator(6524, CloseParam),
                                   Word(6525, "[0];a".to_owned()),
                                   Operator(6530, Dot),
                                   Word(6531, "async".to_owned()),
                                   Operator(6536, Equals),
                                   Word(6537, "1;a".to_owned()),
                                   Operator(6540, Dot),
                                   Word(6541, "src".to_owned()),
                                   Operator(6544, Equals),
                                   Word(6545, "g;m".to_owned()),
                                   Operator(6548, Dot),
                                   Word(6549, "parentNode".to_owned()),
                                   Operator(6559, Dot),
                                   Word(6560, "insertBefore".to_owned()),
                                   Operator(6572, OpenParam),
                                   Word(6573, "a,m".to_owned()),
                                   Operator(6576, CloseParam),
                                   Operator(6578, Newline),
                                   Operator(6591, CloseBrace),
                                   Operator(6592, CloseParam),
                                   Operator(6593, OpenParam),
                                   Word(6594, "window,document,".to_owned()),
                                   Operator(6610, Quote),
                                   Word(6611, "script".to_owned()),
                                   Operator(6617, Quote),
                                   Word(6618, ",".to_owned()),
                                   Operator(6619, Quote),
                                   Operator(6620, ForwardSlash),
                                   Operator(6621, ForwardSlash),
                                   Word(6622, "www".to_owned()),
                                   Operator(6625, Dot),
                                   Word(6626, "google-analytics".to_owned()),
                                   Operator(6642, Dot),
                                   Word(6643, "com".to_owned()),
                                   Operator(6646, ForwardSlash),
                                   Word(6647, "analytics".to_owned()),
                                   Operator(6656, Dot),
                                   Word(6657, "js".to_owned()),
                                   Operator(6659, Quote),
                                   Word(6660, ",".to_owned()),
                                   Operator(6661, Quote),
                                   Word(6662, "ga".to_owned()),
                                   Operator(6664, Quote),
                                   Operator(6665, CloseParam),
                                   Word(6666, ";".to_owned()),
                                   Operator(6668, Newline),
                                   Operator(6670, Newline),
                                   Word(6683, " ga".to_owned()),
                                   Operator(6685, OpenParam),
                                   Operator(6686, Quote),
                                   Word(6687, "create".to_owned()),
                                   Operator(6693, Quote),
                                   Word(6694, ", ".to_owned()),
                                   Operator(6696, Quote),
                                   Word(6697, "UA-49998462-1".to_owned()),
                                   Operator(6710, Quote),
                                   Word(6711, ", ".to_owned()),
                                   Operator(6713, Quote),
                                   Word(6714, "httpete".to_owned()),
                                   Operator(6721, Dot),
                                   Word(6722, "com".to_owned()),
                                   Operator(6725, Quote),
                                   Operator(6726, CloseParam),
                                   Word(6727, ";".to_owned()),
                                   Operator(6729, Newline),
                                   Word(6742, " ga".to_owned()),
                                   Operator(6744, OpenParam),
                                   Operator(6745, Quote),
                                   Word(6746, "send".to_owned()),
                                   Operator(6750, Quote),
                                   Word(6751, ", ".to_owned()),
                                   Operator(6753, Quote),
                                   Word(6754, "pageview".to_owned()),
                                   Operator(6762, Quote),
                                   Operator(6763, CloseParam),
                                   Word(6764, ";".to_owned()),
                                   Operator(6766, Newline),
                                   Operator(6775, CloseBrace),
                                   Operator(6777, Newline),
                                   Operator(6782, CloseBrace),
                                   Operator(6784, Newline),
                                   Operator(6785, CloseBrace)];

        for (actual, expected) in lexer.output().iter().zip(expected_tokens.iter()) {
            assert_eq!(actual, expected);
        }
    }
}
